export const FETCH_DATA = "FETCH_DATA";
export const FILTER_BY_ROCKETNAME = "FILTER_BY_ROCKETNAME";
export const FILTER_BY_STATUS = "FILTER_BY_STATUS";
export const FILTER_BY_ISUPCOMING='FILTER_BY_ISUPCOMING';

